/*****************************************************************************************************************
Author      : MST Solutions
Date        : 6/1/2016
Description : This handler holds the Validation for Required fields and its preventing duplicates. It filter the duplicate
records based on the Wish Type, Case Type Stage and Chapter Name.
*******************************************************************************************************************/

public class ChapterActionTrackHandler {
    
    
}