/***************************************************************************************
Created By:Vennila Paramasivam
Author : MST Solutions
Created Date: 06/01/2016
Description : This util acts as a constant class for having record type values of each object.
****************************************************************************************/

Public Class Constant_AC {
    Public String contactWishChildRT;
    Public String wishDeterminationRT;
    public String wishPlanningAnticipationRT;
    public string wishAssistRT;
    public String wishGrantRT;
    public string wishEffectRT;
    Public String wishFamilyRT;
    public string parentWishRT;
    public String MedicalProfessionalRT;
    public String OrganizationRT;
    public String HouseholdRT;
    public String chapterRT;
    public String OrientationRT;
    public String trainingRT;
    public String volunteerRT;
    public String prospectiveVolunteerRT;
    public String nationalRT;
    public String interviewRT;
    public String taskRT;
    Public String events;
    Public String activeVolRT;
    public String wishVolunteerOpportunity;
    public String backgroundRT;
    public String nonWishEventRT;
    public String nonWishRT;
    public String classOfferingRecordTypeId;
    public String partARecordTypeId;
    public String travelAlgmRT;
    public String budgetingRt;
    public String financeRt;
    public String wishGrantTaskRT;
    public String InKind;
    public String Reimbursement;
    public String diagnosisRT;
    public String wishImapctRT;
    public String boardMemberRT;
    public String hospitalTreatment;
    public String updateContactRT;
    public String registeredWish;
    public String registeredNonWish;
    public String volunteerTaskRT;
    public String staffTaskRT;
    public Constant_AC() {
        staffTaskRT = 'Staff';
        volunteerTaskRT = 'Volunteer';
        diagnosisRT = 'Diagnosis Verification Review';
        budgetingRt = 'Budgeting';
        financeRt = 'Finance';
        contactWishChildRT = 'Wish Child';
        wishDeterminationRT = 'Wish Determination';
        wishPlanningAnticipationRT = 'Wish Planning';
        wishAssistRT = 'Wish Assist';
        wishGrantRT = 'Wish Granting';
        wishEffectRT = 'Wish Impact';
        wishFamilyRT = 'Wish Family';
        parentWishRT = 'Wish';
        MedicalProfessionalRT = 'Medical Professional';
        OrganizationRT = 'Organization';
        HouseholdRT = 'Household Account';
        chapterRT = 'Chapter';
        OrientationRT = 'Orientation';
        trainingRT = 'Training';
        volunteerRT = 'Volunteer Contact';
        prospectiveVolunteerRT = 'Chapter Prospective';
        nationalRT = 'National';
        interviewRT = 'Interview';
        taskRT = 'Default';
        events = 'Events';
        activeVolRT = 'Chapter Active';
        wishVolunteerOpportunity = 'Wish';
        backgroundRT = 'Background Check';
        nonWishEventRT='Non Wish & Event';
        nonWishRT = 'Non Wish';
        classOfferingRecordTypeId = 'Virtual - Self Paced';
        partARecordTypeId = 'Diagnosis Verification Review';
        travelAlgmRT = 'Travel Algorithm';
        wishGrantTaskRT = 'Wish Granted';
        InKind = 'In-Kind Donation';
        Reimbursement = 'Reimbursement';
        wishImapctRT = 'Wish_Effect';
        boardMemberRT = 'Board Member';
        hospitalTreatment = 'Hospital Treatment Facility';
        updateContactRT = 'Contact Updates';
        registeredWish  = 'Volunteer Registered Wish';
        registeredNonWish = 'Volunteer Registered Non Wish';
    }
}