public class RecursiveTriggerHandler{
    public static Boolean isFirstTime = true;
    public static boolean blockCaseLockRecursive = true;
    public static boolean accountRecursive = true;
    public static boolean PartARecursive = true;
    public static boolean accountBeforeUpdate = true;
    public static boolean relationShipRecursive= true;
    public static boolean blockBeforeUpdate = false;
    public static boolean blockAfterUpdate = false;
    public static boolean allowToEditRecord = FALSE;
    Public Static Boolean nationalEmailRecurrence = FALSE;
}