public class RecursiveTriggerHandler{
    public static Boolean isFirstTime = true;
    public static Boolean blockCaseLockRecursive = true;
    public static Boolean accountRecursive = true;
    public static Boolean relationShipRecursive = true;
    public static Boolean blockBeforeUpdate = false;
    public static Boolean blockAfterUpdate = false;
    public static Boolean allowToEditRecord = false;
}